steps:
- name: 'bash'
  args:
  - 'echo'
  - 'Cloud build substitution check: '
  - 'BUILD_ID=$BUILD_ID'
  - 'PROJECT_ID=$PROJECT_ID'
  - 'REVISION_ID=$REVISION_ID'
  - 'REPO_NAME=$REPO_NAME'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'GITHUB_USER=$GITHUB_USER'
  - 'uGITHUB_USER=$_GITHUB_USER'
  - 'TAG_NAME=$TAG_NAME'

# Cloud build has already copied the repo at the tag that
# that triggered the build to its /workspace directory, but
# hasn't actually _cloned_ the repo (there's no .git directory).
#
# The goreleaser tool, however, needs the repo and its history
# to produce release notes.
#
# So clone the repo to /workspace/kustomize
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/${_GITHUB_USER}/kustomize.git']

# Checkout the proper tag.
- name: gcr.io/cloud-builders/git
  dir: kustomize
  args: ['checkout', '$TAG_NAME']

# Run gorelease, but indirectly via a shell script.
- name: goreleaser/goreleaser:v0.138.0
  entrypoint: /bin/sh
  dir: kustomize
  # The final arg here should be '--snapshot' on
  # local build, to suppress the release and leave
  # the 'dist' directory in place.
  args: ['releasing/cloudbuild.sh', '$TAG_NAME']
  secretEnv: ['GITHUB_TOKEN']

# golreleaser expects the GITHUB_TOKEN env var to hold the github token
# it needs to write the released package and notes back to github.
# The raw token was encrypted by gcloud kms (Key Management Service)
# The base64 of that is shown below.  It get decrypted by cloud build
# and provided back to goreleaser.

secrets:
- kmsKeyName: projects/lyrical-gantry-618/locations/global/keyRings/kust-cloud-key-ring/cryptoKeys/kust-cloud-key-name
  secretEnv:
    GITHUB_TOKEN: CiQA2iACN7mMsSYG+jqxUiZyZc5OKJy4iybEVCPZS+bFAYOjyaESUQCRivMAyxoowmb9mWId8BD9XHG2K9he1UAFBgQXNnTIOMZChZZEhXzVDyB7fOOSDYuaHxB5TnNm97euwjVUFxP977jWqXoct6m3ocAf5VBEAQ==

# secrets:
# - kmsKeyName: projects/jregan-corp-gke-dev/locations/global/keyRings/kust-cloud-key-ring/cryptoKeys/kust-cloud-key-name
#   secretEnv:
#     GITHUB_TOKEN: CiQAwfbOkSP4tJf3ZJZMjzHaRPZ2RxiQhORZ3xxlVtpoy8631uQSUACk6WMKjtkpsRkRl+uxWUVvN29M5qveyXjaDDO094/qwsSc8RiYlHYt7Ii1bWkkz3P1kG0nHfG7Fd46A+GJ6R5NhmNfingd/nu9iKrNwLXK
#
#

# secrets:
# - kmsKeyName: projects/lyrical-gantry-618/locations/global/keyRings/kust-cloud-key-ring/cryptoKeys/kust-cloud-key-name
#   secretEnv:
#     GITHUB_TOKEN: CiQA2iACN7mMsSYG+jqxUiZyZc5OKJy4iybEVCPZS+bFAYOjyaESUQCRivMAyxoowmb9mWId8BD9XHG2K9he1UAFBgQXNnTIOMZChZZEhXzVDyB7fOOSDYuaHxB5TnNm97euwjVUFxP977jWqXoct6m3ocAf5VBEAQ==
